version: "3.8"
services:
   postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_DB: my-db
        POSTGRES_USER: my-user
        POSTGRES_PASSWORD: my-pwd
      ports:
        - "5432:5432"
